### ISSUE TITLE
Module Hierarchy Aesthetics

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#153]
It was suggested to consider adjusting the imports of deep modules/classes to a higher level.  For example:

`from aspire.utils.blk_diag_matrix import BlkDiagMatrix`
vs
`from aspire.utils import BlkDiagMatrix`

This is done by adding something like the following to `aspire/utils/__init__.py`:

```
+from .blk_diag_matrix import BlkDiagMatrix
+from .blk_diag_matrix import filter_to_fb_mat
+from .blk_diag_matrix import get_partition
```

I think that would allow either pattern, so it's not a breaking change.  I have no preference.  If the code is clean I would use macros/regexp to edit that stuff, so it purely visual aesthetic to me.  It is worth narrowing down those patterns before we have lots of users, since those might be breaking changes for them if we do it in the future.

**Comment by garrettwrong** [comment]
@janden , what would you like imports to look like, wholesale? (not just for BlkDiagMatrix).  This is probably as good a time as any to establish a practice.  I would be able to convert existing code if it is required.

Examples

`from aspire import Basis` vs `from aspire.basis import Basis`
`from aspire import someutility` vs `from aspire.utils import someutility` vs `from aspire.utils.topic import someutility`
`from aspire import DenoiserCov2d` vs ``from aspire.denoising import DenoiserCov2D` vs `from aspire.denoising.denoiser_cov2d import DenoiserCov2D`

I really don't have a preference other than to say most python projects I have worked on either pick explicit or top level.  The middle variants, while actually looking the most reasonable are harder to define and enforce.  That and mainly, we want to do anything like this before you anticipate having users, or they will get annoyed we're changing things.

If we go explicit, I think this is a no op.

**Comment by janden** [comment]
Gut feeling is the middle level. That is, the interface doesn't go deeper than two levels. My problem with the explicit approach is that it becomes redundant (like `from aspire.denoising.denoiser_cov2d import DenoiserCov2D`).

So it's top level or middle level. What sort of problems tend to crop up with the middle level, in your experience? I'm open to doing everything at the top level, but my worry is that it gets crowded pretty quickly.

**Comment by garrettwrong** [comment]
You are right, top level namespace gets crowded. It's not really my preference for large projects (what ASPIRE wants to be).  It also encourages users to `from aspire import *`, which I don't think we want... Maybe lets not do that.

I agree the middle level is the best aesthetically. The only problem with the middle level is it can sort of be discretionary how to apply it.  I guess we'll just need to keep an eye out for corner cases. I can start doing these, try to knock them out.

**Comment by janden** [comment]
I'm sorry but I still don't follow. What sort of decisions would end up being discretionary? If everything lives at the second level (nothing in the top level and “nothing” [public at least] in the third level), there should be little cause for contention. I could see there being issues with deciding which submodule a given object should be in, but so far, that hasn't been an issue.

Not trying to be difficult. Just trying to understand what I'm overlooking here…

**Comment by garrettwrong** [comment]
Ostensibly saying something like "always second level" seems simple but it may not always be clear (to me) how to delineate what the appropriate size/scope of a second level module is.  For example, something like apple picker or the click code may be larger/deeper.... I think this is one of those things that is clearer to you because of your intimate familiarity with the toolbox.  If the module/API structure is very well established from the Matlab days, and you are happy and confident this will work well, then I would be satisfied this not much of a concern.

I consider you particular, not difficult, its all good.

**Comment by janden** [comment]
Ah I see. I expect the second-level structure that we have right now to remain fairly constant. In other words, we're going to be adding submodules relatively rarely, and it'll be quite obvious when we do so (hopefully). That being said, I should look over the overall structure to make sure that we have a good structure right now before setting things in stone.

**Comment by garrettwrong** [comment]
Cool, that's good. Some concrete examples of where restructuring yield a cleaner API

`from aspire.utils import BlkDiagMatrix` vs `from aspire.blk_diag_matrix import BlkDiagMatrix`
or maybe even `from aspire.numeric import BlkDiagMatrix` or `from aspire.matrix_computations import BlkDiagMatrix` etc.

I mention that because while most repos have a utils catch all, not everything in our utils are actually utilities (in the way that something like "get_version" or compatibility helpers are). You might stuff anything with matrix math from utils in a module.  I peeked around and this was probably the worst offender.

Another clean example might be `aspire.fft`, again from utils, which we are working on now...

**Comment by janden** [comment]
Agreed about utils. I have a feeling this applies more broadly. Am going to sit down and see what kind of organization makes sense to me, then we can discuss.

**Comment by janden** [comment]
Broadly, I think we should have these second-level packages:

- [x] - `picking`: This includes what's currently in `aspire.apple`. Have the `Apple` name defined in `__init__`. Ideally, we shouldn't need to refer to the third level here (98% of use cases should be `from aspire.picking import Apple`). It's a judgment call whether we should make the submodules private here (i.e., `_apple`, `_helper`, `_picking`) or leave as is. (Same applies for other packages below.)
- [x] - `basis`: Same here, we should be able to access the main `Basis` classes through the root.
- [x] - `class2d`/`class3d`: These are just stubs for now, so we may want to remove them for the release. In the future, `class2d` might become `class_averaging`.
- [x] - `commands`: Keep as is.
- [x] - `data`: Goes away (see #315).
- [x] - `denoising`: Keep as is.
- [x] - `estimation`: I'm worried this might grow to big as we simply add every module that vaguely “estimates” something here. It would be better to break it up into three packages: 
- [x]     - `covariance`: Would hold `cov2d` and `cov3d`.
- [x]     - `reconstruction`: Would hold `mean`.
- [x]     - `noise`: Would hold `noise`.
- [x] - `image`/`volume`: Since the `Image` and `Volume` classes are fundamental to the framework, it might make sense to define them in the root, but that might be confusing. An alternative would be to create a common subpackage `array` or `data` that would hold both `Image` and `Volume`.
- [x] - `io`: Would probably be good to rename this to avoid potential clashes with the system `io` package. How about `files` or `storage`?
- [x] - `nufft`: Keep as is.
- [x] - `orientation`: These are all ab initio methods, so it might make sense to rename this `abinitio`. Or we could leave it as `orientation`.
- [x] - `picker`: This just contains stubs. Remove
- [x] - `reconstruct`: Same. Remove.
- [x] - `source`: Keep as is but move `xform.py` to `image` (or `array` or `data` or whatever we call that package).
- [ ] - `utils`: Lots of stuff in here:
- [x]     - `numeric` can get moved into the ASPIRE root.
- [x]     - `blk_diag_matrix` can go in another subpackage `operators` (we may want to add other types of generalized linear operators there later, like the convolutions in `covar3d`).
- [x]     - `cell` is going away soon, from what I understand (?) so we can keep it here for now.
- [x]     - `config` maybe should go into the ASPIRE root.
- [ ]     - `coor_trans` has some functions which are genuinely util-ish. `grid_?d` could be moved to the `array`/`data` package and the rotation stuff should go into the `Rotation` class (#213). Maybe move these into the `utils` root.
- [x]     - `em` consists of two small functions that are only used by CTF filters and should move into the same file (`filters`).
- [x]     - `fft` should be obsolete soon (#298).
- [x]     - `filters` belongs with the `Image` class in `image`/`array`/`data` or in the `operators` package.
- [x]     - `matlab_compat` is going away at some point (hopefully) but can stay here in the meantime.
- [x]     - `matrix` contains some util-ish stuff except `shrink_covar` which could go into `covariance`. Rest can go in the root `utils`.
- [x]     - `misc` can be split up: `src_wiener_coords` goes into `denoiser_cov2d`, `qr_vols_forward` belongs somewhere in `volume`, `powerset` can go into the root of `utils`.
- [x]     - `optimize` could be its own package in the root.
- [x]     - `preprocess` really belongs in `image` or `operators`
- [x]     - `types` can stay, but should maybe be in the `utils` root.

This is just a rough draft. Let's discuss tomorrow and see what makes sense.

**Comment by garrettwrong** [comment]
Cool, thanks for going through everything. This is a lot of work, but I think it would be good to just bite the bullet here, maybe immediately after the inital tox/black work I am drafting now.  It is only going to get harder to do later...

**Comment by janden** [comment]
We discussed this at the dev meeting and the conclusion was that we should indeed get to this after the tox/CI stuff is in.

**Comment by garrettwrong** [comment]
I've encountered some circular dependency wrt `xform.py`.  I did move it to aspire.image, but for now I am skipping exposing at the second level. I will come back to it after I complete the `utils` changes.  Otherwise I was able to cover most of this today.

**Comment by garrettwrong** [comment]
Leaving cleanup of `coor_trans.py` rotations related code for now, that should be done in the related #314, #213 , #195  or similar.

**Comment by garrettwrong** [comment]
Okay, I've completed and pushed into the draft #332 all outlined items above except those I think are relating to active work from Junchao.  I'll leave those (fft, rotation, xform) things for now, though we should cover them since we've done all this now...

Otherwise noting that I think we decided to leave Image/Volume as separate modules, but that's just what I had on my post-it note, and I might have misunderstood. It isn't a problem to converge them, but I'm not sure if any of the names really appealed with me (`data`, `array`,`stacks`,`types`,`structures` etc).  They seem to contain enough to merit being separate modules.

**Comment by janden** [comment]
> Otherwise noting that I think we decided to leave Image/Volume as separate modules

Yes I think we decided them to leave as is (`aspire.image.Image` and `aspire.volume.Volume`) for now. Maybe we'll alias them to something more convenient later, but for now I think it's fine.

**Comment by garrettwrong** [comment]
@junchaoxia , would you be able to cover your part of this (those three remaining components (fft, rotation, xform) which you were actively working on) so we can complete and close it out?

**Comment by garrettwrong** [comment]
Reminding myself the state of this.  `fft` was moved to `numeric` so checked that off.  Will look at the others, maybe can close this out.

**Comment by garrettwrong** [comment]
`xform.py` is in `.image`, checking that off.

**Comment by garrettwrong** [comment]
That leaves rotations. Essentially we have a class, and it's in the place described above so the module side of things seems to be complete.

ASPIRE-Python code is unfortunately still using the older rot functions, but because we already have a smaller scoped issue for that (#195) we can close this one.
